# ANVIL-MANAGED: true
# version: 1.1
# hash: e532310d
# ---------------------------------------------------------
# AUTO-GENERATED BY ANVIL.
# To eject and take manual control, change 'ANVIL-MANAGED' to 'false'.
# ---------------------------------------------------------

import os
import requests
from typing import Dict, Any

def run(**kwargs) -> Dict[str, Any]:
    """
    Get real-time stock data using Alpha Vantage API.
    
    Parameters:
    - symbol (str): Stock symbol to get data for (e.g., 'AAPL', 'MSFT')
    
    Returns:
    Dict containing stock data or error information
    """
    
    # Validate required parameters
    symbol = kwargs.get('symbol')
    if not symbol:
        return {"error": "symbol parameter is required"}
    
    # Check for API key
    api_key = os.environ.get("ALPHA_VANTAGE_API_KEY")
    if not api_key:
        return {
            "error": "ALPHA_VANTAGE_API_KEY environment variable not set", 
            "missing_credential": "ALPHA_VANTAGE_API_KEY"
        }
    
    try:
        # Alpha Vantage API endpoint for real-time stock data
        url = "https://www.alphavantage.co/query"
        params = {
            "function": "GLOBAL_QUOTE",
            "symbol": symbol.upper(),
            "apikey": api_key
        }
        
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        
        data = response.json()
        
        # Check if API returned an error
        if "Error Message" in data:
            return {"error": f"API Error: {data['Error Message']}"}
        
        if "Note" in data:
            return {"error": f"API Limit: {data['Note']}"}
        
        # Extract quote data
        quote = data.get("Global Quote", {})
        if not quote:
            return {"error": f"No data found for symbol: {symbol}"}
        
        return {
            "symbol": quote.get("01. symbol", ""),
            "price": float(quote.get("05. price", 0)),
            "change": float(quote.get("09. change", 0)),
            "change_percent": quote.get("10. change percent", ""),
            "volume": int(quote.get("06. volume", 0)),
            "previous_close": float(quote.get("08. previous close", 0)),
            "open": float(quote.get("02. open", 0)),
            "high": float(quote.get("03. high", 0)),
            "low": float(quote.get("04. low", 0)),
            "latest_trading_day": quote.get("07. latest trading day", "")
        }
        
    except requests.exceptions.RequestException as e:
        return {"error": f"Network error: {str(e)}"}
    except ValueError as e:
        return {"error": f"Data parsing error: {str(e)}"}
    except Exception as e:
        return {"error": f"Unexpected error: {str(e)}"}