# ANVIL-MANAGED: true
# version: 1.1
# hash: 255055a4
# ---------------------------------------------------------
# AUTO-GENERATED BY ANVIL.
# To eject and take manual control, change 'ANVIL-MANAGED' to 'false'.
# ---------------------------------------------------------

import os
import requests
from typing import Dict, Any

def run(**kwargs) -> Dict[str, Any]:
    """
    Get current weather data for a specified city using OpenWeatherMap API.
    
    Parameters:
    - city (str): Name of the city to get weather for (required)
    - units (str): Temperature units ('metric', 'imperial', 'kelvin'), defaults to 'metric'
    
    Returns:
    Dict with weather data or error message
    """
    
    # Check for required parameters
    city = kwargs.get('city')
    if not city:
        return {"error": "city parameter is required"}
    
    # Get API key from environment
    api_key = os.environ.get("OPENWEATHERMAP_API_KEY")
    if not api_key:
        return {
            "error": "OPENWEATHERMAP_API_KEY environment variable not set", 
            "missing_credential": "OPENWEATHERMAP_API_KEY"
        }
    
    # Get optional parameters
    units = kwargs.get('units', 'metric')
    
    try:
        # Make API request to OpenWeatherMap
        url = "https://api.openweathermap.org/data/2.5/weather"
        params = {
            'q': city,
            'appid': api_key,
            'units': units
        }
        
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        
        data = response.json()
        
        # Extract relevant weather information
        weather_info = {
            "city": data['name'],
            "country": data['sys']['country'],
            "temperature": data['main']['temp'],
            "feels_like": data['main']['feels_like'],
            "humidity": data['main']['humidity'],
            "pressure": data['main']['pressure'],
            "description": data['weather'][0]['description'],
            "wind_speed": data['wind']['speed'],
            "units": units
        }
        
        return {"weather": weather_info}
        
    except requests.exceptions.RequestException as e:
        return {"error": f"Failed to fetch weather data: {str(e)}"}
    except KeyError as e:
        return {"error": f"Unexpected API response format: missing {str(e)}"}
    except Exception as e:
        return {"error": f"An unexpected error occurred: {str(e)}"}